### ISSUE TITLE
QUESTION: How to install this plugin if i'm not using grunt in my project?

### ISSUE THREAD

**Issue by andrei-sheina** [JamesMGreene/qunit-assert-close#7]
Hello. I am new to QUnit and testing and i have troubles installing this plugin. I am using ember-cli for running tests in my project and have no grunt installed. Can you please tell me, how should i install this plugin to use it in my tests?

**Comment by JamesMGreene** [comment]
Grunt is only used to test this plugin itself, it is not required for consumers of this plugin.

For installation, you can either use NPM or download the tarball (or the single "qunit-assert-close.js" file) from GitHub.

To install via NPM:

```shell
$ npm install --save-dev qunit-assert-close
```
