### ISSUE TITLE
qunit-assert-close isn't compatible with QUnit v2.X anymore

### ISSUE THREAD

**Issue by Abszissex** [JamesMGreene/qunit-assert-close#8]
The plugin isn't compatibel with QUnit v2.X.

![qunit error](https://cloud.githubusercontent.com/assets/4190798/18577668/7a75da68-7beb-11e6-9c4f-3ae75b8bf06f.PNG)

see the [upgrade guide to 2.X](http://qunitjs.com/upgrade-guide-2.x/)

**Comment by JamesMGreene** [comment]
Fixed in 2dfc9e6. Published as `v2.1.0`. Thanks!

**Comment by JamesMGreene** [comment]
P.S. Basically a duplicate of #4.
